// Generated by Trezor with passphrase "robiniscool"

export const legacyAccountBTC = {
  extendedKey:
    "xpub6Cw9YG38NXy6zQGPziJo7pLrzemwdyyMYVAaHZRXwcmfjsfRaQJmbyxkxzL1pE1u3898bKriUkaTK6GtRPCnryZjGZoAi8HPkDr6ns63nus",
  publicKeys: [
    "0367359c51b41e7e3f5648161b063c7a6d8c8bc25482c337106469e9d6d75e908f",
  ],
  addresses: ["195nYLPg9NTdCzTeZT9Db5txc1FRAJC7UH"],
};

export const segWitAccountBTC = {
  extendedKey:
    "zpub6rhiffzBcHgg2pcxDqGABAG92kvZMNPT32wrKLg97FWzHcwussvBaUqY8agEWiQT2QH1uoCbHz51cZVJJTnmnkdhtc7RnFgsYwiVaGtCUS8",
  publicKeys: [
    "02d02f92658c13da93fd9660a087428523d16756533f1221a5c081b9e80094f3f9",
  ],
  addresses: ["bc1qmw8ahz6a68j4cvgmlt3v00js0mw2pvpg44czur"],
};

export const tapRootAccountBTC = {
  extendedKey:
    "tr([5c9e228d/86'/0'/0']xpub6DRrbqJmCjK1KYTHQZs1C3pE7XrJcUHfYPoXi4UmYSDNsQjhp2z24YHRrCzyPJAGgbvmUqoyo1kvQxQp9jXhyKgfxfRdos2DJM7ReD9ddkK/<0;1>/*)",
  addresses: ["bc1p0g23k24ksj444v65f3jmg9y59cj82x2mp5kn7zdsnlfvmfmaxxusz7cddv"],
};